export type LandingPage = {
  slug: string;
  title: string;
  subtitle: string;
  metaDescription: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  audience: string[];
  outcomes: string[];
  relatedPackageSlugs: string[];
  backlinks: string[];
  marketNote: string;
};

export const landingPages: LandingPage[] = [
  {
    slug: "ats-cv-writing-service-sri-lanka",
    title: "ATS CV Writing Service in Sri Lanka",
    subtitle: "Professional ATS-Friendly CVs for Job Seekers in Sri Lanka and Overseas",
    metaDescription:
      "Get a professional ATS-friendly CV in Sri Lanka with clear role alignment, recruiter-focused writing, and keyword optimization.",
    primaryKeyword: "ATS CV Writing Service in Sri Lanka",
    secondaryKeywords: [
      "professional CV writing service Sri Lanka",
      "ATS friendly CV",
      "CV writer Sri Lanka",
      "resume writing service Sri Lanka",
      "foreign job CV Sri Lanka",
    ],
    audience: [
      "Fresh graduates and internship applicants",
      "Experienced professionals planning a career move",
      "Executives and managers applying for senior roles",
      "Foreign job applicants targeting GCC, UK, Canada, and Australia",
    ],
    outcomes: [
      "Clearer first impression with recruiters",
      "Better ATS readability and keyword alignment",
      "Achievement-focused positioning instead of task-only wording",
      "Role-specific document quality for local and overseas applications",
    ],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "ats-cv-professional-supervised"],
    backlinks: [
      "professional-cv-writing-service-sri-lanka",
      "cover-letter-writing-service",
      "linkedin-profile-optimization-sri-lanka",
      "foreign-job-cv-writing-service",
      "professional-cv-review-service",
    ],
    marketNote:
      "This page is built for job seekers in Sri Lanka who need ATS-safe documents for competitive local and international hiring processes.",
  },
  {
    slug: "professional-cv-writing-service-sri-lanka",
    title: "Professional CV Writing Service in Sri Lanka",
    subtitle: "Role-Targeted CV Writing for Stronger Interview Conversion",
    metaDescription:
      "Professional CV writing service in Sri Lanka with ATS-ready formatting, achievement-focused content, and recruiter-friendly structure.",
    primaryKeyword: "Professional CV Writing Service in Sri Lanka",
    secondaryKeywords: ["CV writing Sri Lanka", "professional resume writing", "ATS CV writer", "career CV service"],
    audience: ["Mid-level professionals", "Career changers", "Promotion-focused applicants", "Private and public sector candidates"],
    outcomes: ["Sharper career narrative", "Industry-relevant keyword strategy", "Cleaner layout and readability", "Stronger shortlisting confidence"],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "ats-cv-professional-founder-led", "ats-cv-executive-founder-led"],
    backlinks: ["ats-cv-writing-service-sri-lanka", "cover-letter-writing-service", "cv-linkedin-optimization-package", "it-cv-writing-service"],
    marketNote: "Designed for candidates who need a practical, interview-focused CV upgrade for the Sri Lankan job market.",
  },
  {
    slug: "executive-cv-writing-service",
    title: "Executive CV Writing Service",
    subtitle: "Leadership-Focused CV Strategy for Senior Professionals",
    metaDescription:
      "Executive CV writing service for directors, senior managers, and C-level professionals with strategic, impact-focused positioning.",
    primaryKeyword: "Executive CV Writing Service",
    secondaryKeywords: ["executive CV writer", "senior management CV", "leadership resume", "director CV writing"],
    audience: ["Directors", "Senior managers", "C-level applicants", "Board-facing leaders"],
    outcomes: ["Leadership impact visibility", "Strategic narrative clarity", "Executive-level language quality", "Better fit for senior hiring"],
    relatedPackageSlugs: ["ats-cv-executive-founder-led", "ats-cv-executive-supervised", "linkedin-executive-founder-led"],
    backlinks: ["professional-cv-review-service", "linkedin-profile-optimization-sri-lanka", "career-document-package", "ats-cv-writing-service-sri-lanka"],
    marketNote: "Built for leadership hiring where outcome-driven communication and strategic positioning matter most.",
  },
  {
    slug: "fresh-graduate-cv-writing-service",
    title: "Fresh Graduate CV Writing Service",
    subtitle: "Build a Strong First CV for Internship and Entry-Level Roles",
    metaDescription:
      "Fresh graduate CV writing service in Sri Lanka to turn education, projects, and internships into a professional ATS-friendly profile.",
    primaryKeyword: "Fresh Graduate CV Writing Service",
    secondaryKeywords: ["graduate CV Sri Lanka", "entry level CV writing", "internship CV", "student resume writer"],
    audience: ["University graduates", "School leavers", "Internship applicants", "Early-career job seekers"],
    outcomes: ["Stronger first-job positioning", "Clear project and internship storytelling", "ATS-compatible structure", "Higher application confidence"],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "cover-letter-student-founder-led", "cover-letter-professional-founder-led", "ats-cv-student-supervised"],
    backlinks: ["ats-cv-writing-service-sri-lanka", "cover-letter-writing-service", "professional-cv-writing-service-sri-lanka", "linkedin-profile-optimization-sri-lanka"],
    marketNote: "Focused on freshers who need practical presentation quality despite limited experience.",
  },
  {
    slug: "foreign-job-cv-writing-service",
    title: "Foreign Job CV Writing Service",
    subtitle: "International-Ready CVs for Overseas Job Applications",
    metaDescription:
      "Foreign job CV writing service for Sri Lankan applicants targeting GCC, UK, Europe, Canada, and Australia with role-specific formatting.",
    primaryKeyword: "Foreign Job CV Writing Service",
    secondaryKeywords: ["overseas CV writing", "international resume", "GCC job CV", "foreign employment CV Sri Lanka"],
    audience: ["Gulf job applicants", "Migration applicants", "International professionals", "Skilled workers"],
    outcomes: ["Country-aware CV presentation", "Clear achievement communication", "Role-aligned keyword strategy", "Better global recruiter readability"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "cover-letter-professional-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["dubai-cv-writing-service", "uae-cv-writing-service", "canada-resume-writing-service", "australia-resume-writing-service"],
    marketNote: "Useful for candidates applying to overseas roles that require stronger standardization and international resume conventions.",
  },
  {
    slug: "linkedin-profile-optimization-sri-lanka",
    title: "LinkedIn Profile Optimization Sri Lanka",
    subtitle: "Improve Recruiter Visibility with Strategic LinkedIn Positioning",
    metaDescription:
      "LinkedIn profile optimization in Sri Lanka including headline, about section, keywords, and experience positioning.",
    primaryKeyword: "LinkedIn Profile Optimization Sri Lanka",
    secondaryKeywords: ["LinkedIn optimization", "LinkedIn profile writer", "recruiter visibility", "personal branding LinkedIn"],
    audience: ["Active job seekers", "Freelancers", "Managers", "Professionals building personal brand"],
    outcomes: ["Better profile search visibility", "Stronger first impression", "Aligned CV + LinkedIn story", "Improved recruiter trust"],
    relatedPackageSlugs: ["linkedin-student-founder-led", "linkedin-professional-founder-led", "linkedin-executive-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["ats-cv-writing-service-sri-lanka", "cv-linkedin-optimization-package", "career-document-package", "professional-cv-writing-service-sri-lanka"],
    marketNote: "Ideal when your CV is strong but your LinkedIn profile does not reflect the same professional value.",
  },
  {
    slug: "cover-letter-writing-service",
    title: "Cover Letter Writing Service",
    subtitle: "Role-Specific Cover Letters That Strengthen Your Application",
    metaDescription:
      "Professional cover letter writing service for local and overseas applications with clear positioning and role relevance.",
    primaryKeyword: "Cover Letter Writing Service",
    secondaryKeywords: ["cover letter writing Sri Lanka", "job application letter", "professional cover letter", "foreign job cover letter"],
    audience: ["Fresh graduates", "Mid-level professionals", "Career changers", "International applicants"],
    outcomes: ["Stronger role alignment", "More personalized applications", "Improved document consistency", "Cleaner communication of value"],
    relatedPackageSlugs: ["cover-letter-student-founder-led", "cover-letter-professional-founder-led", "cover-letter-executive-founder-led", "cover-letter-professional-supervised"],
    backlinks: ["cv-cover-letter-package", "ats-cv-writing-service-sri-lanka", "professional-cv-writing-service-sri-lanka", "foreign-job-cv-writing-service"],
    marketNote: "Useful when you need to explain relevance, motivation, and value beyond your CV in competitive applications.",
  },
  {
    slug: "cv-cover-letter-package",
    title: "CV + Cover Letter Package",
    subtitle: "Two Core Job Application Documents in One Aligned Package",
    metaDescription:
      "Get a CV and cover letter package with aligned messaging, ATS-ready formatting, and stronger application consistency.",
    primaryKeyword: "CV + Cover Letter Package",
    secondaryKeywords: ["CV and cover letter bundle", "application duo", "career document package", "ATS CV + letter"],
    audience: ["Active applicants", "Fresh graduates", "Role switchers", "Foreign job seekers"],
    outcomes: ["Consistent document message", "Faster application readiness", "Improved ATS and recruiter clarity", "Higher confidence before applying"],
    relatedPackageSlugs: ["cover-letter-professional-supervised", "ats-cv-professional-founder-led", "cover-letter-professional-founder-led"],
    backlinks: ["cover-letter-writing-service", "professional-cv-writing-service-sri-lanka", "career-document-package", "foreign-job-cv-writing-service"],
    marketNote: "Best for applicants who want both primary documents professionally aligned before high-volume job applications.",
  },
  {
    slug: "cv-linkedin-optimization-package",
    title: "CV + LinkedIn Optimization Package",
    subtitle: "Align Your CV and LinkedIn Profile for Better Hiring Visibility",
    metaDescription:
      "CV + LinkedIn package to align document quality and profile positioning for stronger recruiter trust and visibility.",
    primaryKeyword: "CV + LinkedIn Optimization Package",
    secondaryKeywords: ["CV and LinkedIn package", "LinkedIn plus CV", "career branding package", "profile alignment"],
    audience: ["Professionals in transition", "Mid-level candidates", "Leaders", "Global applicants"],
    outcomes: ["Unified professional brand", "Higher LinkedIn relevance", "Document and profile consistency", "Better recruiter response quality"],
    relatedPackageSlugs: ["ats-cv-professional-supervised", "ats-cv-professional-founder-led", "linkedin-professional-founder-led"],
    backlinks: ["linkedin-profile-optimization-sri-lanka", "ats-cv-writing-service-sri-lanka", "career-document-package", "executive-cv-writing-service"],
    marketNote: "Strong choice for candidates who want both ATS document quality and online professional visibility.",
  },
  {
    slug: "career-document-package",
    title: "Career Document Package",
    subtitle: "Complete Career Documents for Local and Overseas Job Search",
    metaDescription:
      "Career document package with CV writing, cover letter support, and LinkedIn alignment for end-to-end application quality.",
    primaryKeyword: "Career Document Package",
    secondaryKeywords: ["career documents", "complete job application package", "CV cover letter LinkedIn", "career branding package"],
    audience: ["Serious applicants", "Promotion seekers", "Foreign job applicants", "Career changers"],
    outcomes: ["End-to-end consistency", "Stronger hiring narrative", "Professional formatting and keyword strategy", "Faster decision-ready profile"],
    relatedPackageSlugs: ["ats-cv-professional-supervised", "cover-letter-professional-supervised", "ats-cv-professional-founder-led", "linkedin-professional-founder-led"],
    backlinks: ["cv-cover-letter-package", "cv-linkedin-optimization-package", "professional-cv-writing-service-sri-lanka", "cover-letter-writing-service"],
    marketNote: "Recommended when you need full application support rather than one standalone document.",
  },
  {
    slug: "dubai-cv-writing-service",
    title: "Dubai CV Writing Service",
    subtitle: "Targeted CV Writing for Dubai and UAE Job Opportunities",
    metaDescription:
      "Dubai CV writing service for Sri Lankan job seekers applying to UAE roles with clear structure, ATS compatibility, and role alignment.",
    primaryKeyword: "Dubai CV Writing Service",
    secondaryKeywords: ["Dubai resume", "UAE job CV", "Gulf CV writing", "foreign job CV Dubai"],
    audience: ["Dubai job applicants", "Hospitality and logistics candidates", "Admin and operations professionals", "GCC transfer seekers"],
    outcomes: ["Better GCC-market positioning", "Cleaner recruiter readability", "Improved role alignment", "Higher confidence in cross-border applications"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "cover-letter-professional-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["uae-cv-writing-service", "foreign-job-cv-writing-service", "cover-letter-writing-service", "ats-cv-writing-service-sri-lanka"],
    marketNote: "Built for Dubai-focused applicants who need practical CV quality for fast, high-volume hiring environments.",
  },
  {
    slug: "uae-cv-writing-service",
    title: "UAE CV Writing Service",
    subtitle: "ATS-Friendly CVs for UAE Job Market Applications",
    metaDescription:
      "UAE CV writing service in Sri Lanka for applicants targeting Abu Dhabi, Dubai, Sharjah and wider Gulf opportunities.",
    primaryKeyword: "UAE CV Writing Service",
    secondaryKeywords: ["UAE resume writing", "Gulf job CV", "ATS CV for UAE", "foreign CV writing"],
    audience: ["UAE applicants", "Skilled workers", "Office and technical staff", "Experienced professionals"],
    outcomes: ["Better country-fit formatting", "Role-focused content quality", "Improved initial screening performance", "Stronger first impression"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "cover-letter-professional-founder-led", "cover-letter-professional-supervised"],
    backlinks: ["dubai-cv-writing-service", "foreign-job-cv-writing-service", "canada-resume-writing-service", "australia-resume-writing-service"],
    marketNote: "Useful for candidates who need UAE-targeted positioning with ATS-ready structure and language clarity.",
  },
  {
    slug: "canada-resume-writing-service",
    title: "Canada Resume Writing Service",
    subtitle: "International Resume Support for Canada Job Applications",
    metaDescription:
      "Canada resume writing service for Sri Lankan applicants with concise ATS-friendly structure, role-specific keywords, and market-aligned formatting.",
    primaryKeyword: "Canada Resume Writing Service",
    secondaryKeywords: ["Canada resume", "resume writer for Canada", "international resume", "foreign job resume"],
    audience: ["Migration-path applicants", "Skilled professionals", "IT and engineering candidates", "Healthcare applicants"],
    outcomes: ["Resume format aligned to Canadian expectations", "Cleaner achievement presentation", "Keyword-supported ATS readiness", "Stronger role fit communication"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "cover-letter-professional-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["australia-resume-writing-service", "foreign-job-cv-writing-service", "linkedin-profile-optimization-sri-lanka", "professional-cv-review-service"],
    marketNote: "Designed for candidates needing concise, achievement-driven resume standards commonly preferred in Canada.",
  },
  {
    slug: "australia-resume-writing-service",
    title: "Australia Resume Writing Service",
    subtitle: "Professional Resume Support for Australia Job Market",
    metaDescription:
      "Australia resume writing service for role-targeted, ATS-friendly resumes for skilled migration and direct hiring applications.",
    primaryKeyword: "Australia Resume Writing Service",
    secondaryKeywords: ["Australia resume", "resume writer Australia", "international resume writing", "ATS resume service"],
    audience: ["Australia applicants", "Technical professionals", "Skilled migration candidates", "Mid-level managers"],
    outcomes: ["Market-suitable resume style", "Clear and concise impact language", "Role-focused keyword structure", "Improved recruiter readability"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "cover-letter-professional-founder-led", "linkedin-professional-founder-led"],
    backlinks: ["canada-resume-writing-service", "foreign-job-cv-writing-service", "cover-letter-writing-service", "cv-linkedin-optimization-package"],
    marketNote: "Prepared for applicants targeting Australia where concise, outcome-led resume content is usually preferred.",
  },
  {
    slug: "it-cv-writing-service",
    title: "IT CV Writing Service",
    subtitle: "Technical CV Writing for Software, QA, Data, and Infrastructure Roles",
    metaDescription:
      "IT CV writing service with ATS-focused keyword strategy for software engineering, QA, data, cloud, and support professionals.",
    primaryKeyword: "IT CV Writing Service",
    secondaryKeywords: ["software engineer CV", "QA CV writing", "data analyst CV", "technical resume writer"],
    audience: ["Software engineers", "QA and testing professionals", "Data analysts", "Infrastructure and support engineers"],
    outcomes: ["Better technical keyword alignment", "Clear project and stack presentation", "Recruiter-friendly structure", "Stronger role relevance"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-professional-supervised", "linkedin-professional-founder-led"],
    backlinks: ["engineering-cv-writing-service", "finance-cv-writing-service", "professional-cv-writing-service-sri-lanka", "ats-cv-writing-service-sri-lanka"],
    marketNote: "Built for technical job seekers whose CVs must balance ATS keyword depth and clear business impact communication.",
  },
  {
    slug: "banking-cv-writing-service",
    title: "Banking CV Writing Service",
    subtitle: "ATS-Friendly CV Writing for Banking and Financial Services Roles",
    metaDescription:
      "Banking CV writing service for operations, relationship management, risk, compliance, and branch-level roles.",
    primaryKeyword: "Banking CV Writing Service",
    secondaryKeywords: ["banking CV", "bank job resume", "finance sector CV", "ATS CV banking"],
    audience: ["Retail banking professionals", "Operations and teller staff", "Relationship officers", "Risk and compliance candidates"],
    outcomes: ["Stronger sector-specific language", "Improved compliance and process clarity", "Achievement-led role positioning", "Better shortlist readiness"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-professional-supervised", "cover-letter-professional-founder-led"],
    backlinks: ["finance-cv-writing-service", "professional-cv-review-service", "cover-letter-writing-service", "ats-cv-writing-service-sri-lanka"],
    marketNote: "Created for banking candidates who need structured and trustworthy professional presentation.",
  },
  {
    slug: "finance-cv-writing-service",
    title: "Finance CV Writing Service",
    subtitle: "Professional CV Writing for Accounting, Audit, and Finance Careers",
    metaDescription:
      "Finance CV writing service for accountants, auditors, analysts, and finance professionals with ATS-safe structure and impact-focused wording.",
    primaryKeyword: "Finance CV Writing Service",
    secondaryKeywords: ["accounting CV", "audit CV", "finance resume", "CIMA ACCA CV writing"],
    audience: ["Accountants", "Auditors", "Financial analysts", "Finance executives"],
    outcomes: ["Better financial impact communication", "Clearer tools and standards visibility", "ATS-aligned role targeting", "Professional formatting quality"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-professional-supervised", "cover-letter-professional-founder-led"],
    backlinks: ["banking-cv-writing-service", "professional-cv-writing-service-sri-lanka", "foreign-job-cv-writing-service", "canada-resume-writing-service"],
    marketNote: "Best for finance professionals needing stronger clarity in reporting, controls, compliance, and business outcomes.",
  },
  {
    slug: "engineering-cv-writing-service",
    title: "Engineering CV Writing Service",
    subtitle: "ATS-Optimized CVs for Engineering and Technical Roles",
    metaDescription:
      "Engineering CV writing service for mechanical, civil, electrical, and industrial professionals with keyword-optimized ATS formatting.",
    primaryKeyword: "Engineering CV Writing Service",
    secondaryKeywords: ["engineering CV", "technical CV writer", "civil engineer resume", "mechanical engineer CV"],
    audience: ["Civil engineers", "Mechanical engineers", "Electrical engineers", "Site and project engineers"],
    outcomes: ["Clear project and technical scope presentation", "Better standards and tools visibility", "Achievement-focused wording", "Higher role alignment"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["it-cv-writing-service", "healthcare-cv-writing-service", "foreign-job-cv-writing-service", "dubai-cv-writing-service"],
    marketNote: "Helpful for engineering candidates who need practical proof-based content instead of generic responsibility lists.",
  },
  {
    slug: "healthcare-cv-writing-service",
    title: "Healthcare CV Writing Service",
    subtitle: "Professional CV Writing for Healthcare and Clinical Careers",
    metaDescription:
      "Healthcare CV writing service for nurses, pharmacists, lab professionals, and allied health candidates with ATS-friendly structure.",
    primaryKeyword: "Healthcare CV Writing Service",
    secondaryKeywords: ["nursing CV", "pharmacist resume", "medical CV writing", "healthcare job CV"],
    audience: ["Nurses", "Pharmacists", "Lab technologists", "Allied healthcare professionals"],
    outcomes: ["Clear clinical and patient-care positioning", "Better certification and compliance visibility", "Role-targeted keyword optimization", "Improved recruiter readability"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "cover-letter-professional-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["engineering-cv-writing-service", "finance-cv-writing-service", "foreign-job-cv-writing-service", "professional-cv-review-service"],
    marketNote: "Designed for healthcare candidates where clarity, compliance, and trust-based communication are essential.",
  },
  {
    slug: "professional-cv-review-service",
    title: "Professional CV Review Service",
    subtitle: "Expert CV Feedback to Improve ATS Performance and Recruiter Readability",
    metaDescription:
      "Professional CV review service with ATS recommendations, content fixes, and structure guidance for stronger interview conversion.",
    primaryKeyword: "Professional CV Review Service",
    secondaryKeywords: ["CV review Sri Lanka", "ATS CV review", "resume feedback", "professional CV audit"],
    audience: ["Applicants with an existing CV", "Mid-level professionals", "Executive candidates", "Foreign job applicants"],
    outcomes: ["Clear fix list before applying", "Improved ATS keyword coverage", "Better section flow and clarity", "Faster CV quality upgrade"],
    relatedPackageSlugs: ["ats-cv-professional-supervised", "ats-cv-executive-supervised", "ats-cv-fresh-graduate-supervised"],
    backlinks: ["ats-cv-writing-service-sri-lanka", "professional-cv-writing-service-sri-lanka", "executive-cv-writing-service", "it-cv-writing-service"],
    marketNote: "Best for candidates who already have a CV but want expert correction before high-priority applications.",
  },
  // --- SINHALA LANDING PAGES ---
  {
    slug: "professional-cv-writing-service-sri-lanka-sinhala",
    title: "ශ්‍රී ලංකාවේ Professional CV Writing Service",
    subtitle: "ඔබේ සිහින රැකියාවට යන්න, ATS-Friendly Professional CV එකකින් පටන්ගන්න.",
    metaDescription: "ශ්‍රී ලංකාවේ රැකියා සඳහා ගැලපෙන, ATS-Friendly Professional CV සකස් කිරීමේ සේවාව. අදම ඔබේ CV එක වෘත්තීය මට්ටමකට ගෙන එන්න.",
    primaryKeyword: "Professional CV Writing Service Sri Lanka",
    secondaryKeywords: ["CV නිර්මාණය", "CV writing Sinhala", "professional CV Sri Lanka", "CV හදන අය"],
    audience: ["රැකියා සොයන සියලුම දෙනා", "කළමනාකරුවන්", "වෘත්තිකයන්", "විශ්වවිද්‍යාල සිසුන්"],
    outcomes: ["ATS මෘදුකාංග මගින් තෝරාගැනීමේ සම්භාවිතාව වැඩිවීම", "කෙටි කාලයකින් Interview Calls ලැබීම", "ඔබේ සුදුසුකම් ආකර්ශනීයව ඉදිරිපත් වීම", "වෘත්තීය පෙනුමක් ඇති CV එකක් ලැබීම"],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "ats-cv-professional-founder-led", "ats-cv-executive-founder-led"],
    backlinks: ["create-ats-friendly-cv-sinhala", "cv-review-service-sinhala", "professional-cv-writing-service-sri-lanka"],
    marketNote: "Sinhala localized page for top-tier Sri Lankan job seekers.",
  },
  {
    slug: "create-ats-friendly-cv-sinhala",
    title: "ATS Friendly CV එකක් හදාගන්න",
    subtitle: "නවීන සමාගම් වල Applicant Tracking System (ATS) ජයගන්නා CV එකක් සකසා ගන්න.",
    metaDescription: "ATS මෘදුකාංග සඳහා ගැලපෙන ATS Friendly CV එකක් සකසා ගන්න. Rejected වන CV එක වෙනුවට Interview calls එන CV එකක් ලබාගන්න.",
    primaryKeyword: "ATS Friendly CV Sinhala",
    secondaryKeywords: ["ATS friendly CV එකක් හදාගන්න", "ATS resume Sri Lanka", "CV format Sinhala"],
    audience: ["Job portals හරහා apply කරන අය", "පෞද්ගලික අංශයේ රැකියා සොයන අය", "විදේශ රැකියා සොයන අය"],
    outcomes: ["CV එක reject වීම අවම වීම", "Keyword optimization හරහා ඉදිරියට පැමිණීම", "අන්තර්ජාතික ප්‍රමිතියට CV එක සැකසීම"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "ats-cv-professional-supervised"],
    backlinks: ["professional-cv-writing-service-sri-lanka-sinhala", "create-professional-cv-for-jobs-sinhala", "ats-cv-writing-service-sri-lanka"],
    marketNote: "Educational angle to explain ATS basics while selling the CV package.",
  },
  {
    slug: "create-professional-cv-for-jobs-sinhala",
    title: "රැකියා සඳහා Professional CV එකක් හදාගන්න",
    subtitle: "තරඟකාරී රැකියා වෙළඳපොලේ කැපී පෙනෙන, Professional CV එකක් අදම සකසා ගන්න.",
    metaDescription: "ඔබගේ හැකියාවන් සහ පළපුරුද්ද නිවැරදිව පෙන්වන වෘත්තීය CV එකක් සාදා ගන්න. සම්මුඛ පරීක්ෂණ අවස්ථා වැඩි කරගන්න.",
    primaryKeyword: "Professional CV for Jobs Sri Lanka",
    secondaryKeywords: ["රැකියා CV", "professional CV in Sinhala", "CV සකස් කිරීම"],
    audience: ["රැකියාවක් සොයන ඕනෑම අයෙක්", "වෘත්තීය ජීවිතය අලුතින් පටන් ගන්නා අය", "රැකියාව මාරු කිරීමට බලාපොරොත්තු වන අය"],
    outcomes: ["ආකර්ෂණීය පෙනුමකින් යුත් CV එකක්", "ඔබේ අත්දැකීම් පැහැදිලිව සඳහන් වීම", "රැකියාවට අදාලව විශේෂයෙන් සකසන ලද (Tailored) අන්තර්ගතය", "ඉහළ ප්‍රතිචාර අනුපාතයක්"],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "ats-cv-professional-founder-led", "cover-letter-professional-founder-led"],
    backlinks: ["create-ats-friendly-cv-sinhala", "cv-make-for-interview-calls-sinhala", "fresh-graduate-cv-writing-sinhala"],
    marketNote: "General awareness page for creating a professional CV for local jobs.",
  },
  {
    slug: "cv-make-for-interview-calls-sinhala",
    title: "Interview Calls එන CV එකක් හදාගන්න",
    subtitle: "Apply කරාට කතා කරන්නේ නැද්ද? Interview Calls ගෙනෙන සාර්ථක CV එකක් හදාගන්න.",
    metaDescription: "අයදුම්පත් යැව්වත් interview calls එන්නේ නැත්නම්, අඩුපාඩු හදාගෙන interview calls ගෙනෙන සාර්ථක CV එකක් අදම හදාගන්න.",
    primaryKeyword: "CV for Interview Calls",
    secondaryKeywords: ["interview calls CV", "get more interviews", "CV එකක් සාර්ථකව හදමු", "why my cv rejected"],
    audience: ["වෙහෙස වී apply කරන නමුත් ප්‍රතිචාර නොලබන අය", "රැකියා අවස්ථා අහිමි වන අය"],
    outcomes: ["HR කළමනාකරුවන්ගේ අවධානය දිනාගැනීම", "CV එකේ ඇති දුර්වලතා මගහරවා ගැනීම", "අනවශ්‍ය තොරතුරු ඉවත් කර වැදගත් දේ ඉස්මතු කිරීම", "වැඩි සම්මුඛ පරීක්ෂණ අවස්ථා ප්‍රමාණයක්"],
    relatedPackageSlugs: ["ats-cv-professional-supervised", "ats-cv-professional-founder-led", "ats-cv-executive-founder-led"],
    backlinks: ["create-professional-cv-for-jobs-sinhala", "cv-review-service-sinhala", "professional-cv-writing-service-sri-lanka-sinhala"],
    marketNote: "Slightly pain-point focused-targeting frustrated job hunters.",
  },
  {
    slug: "fresh-graduate-cv-writing-sinhala",
    title: "Fresh Graduate CV එකක් හදාගන්න",
    subtitle: "පළපුරුද්දක් නැති වුනත් රැකියාවකට යන්න පුලුවන්, ආකර්ෂණීය Graduate CV එකක් සකස් කරගන්න.",
    metaDescription: "විශ්වවිද්‍යාලයෙන් හෝ උසස් අධ්‍යාපනයෙන් පසු පළමු රැකියාව සොයන ඔබට විශේෂයෙන් සැකසූ Graduate CV writing සේවාව.",
    primaryKeyword: "Fresh Graduate CV Sinhala",
    secondaryKeywords: ["university graduate CV", "school leavers resume", "First job CV Sinhala", "student CV"],
    audience: ["විශ්වවිද්‍යාල සිසුන්", "පාසල් නිමකල අය", "ප්‍රථම රැකියාව අපේක්ෂා කරන අය"],
    outcomes: ["අධ්‍යාපනික සුදුසුකම් ඉස්මතු කර දැක්වීම", "විෂය බාහිර ක්‍රියාකාරකම් සහ soft skills මනා ලෙස ඉදිරිපත් කිරීම", "Professional Industry Standard එකට හුරුවීම", "පළමු රැකියාවට ඉක්මනින් පිවිසීම"],
    relatedPackageSlugs: ["ats-cv-student-founder-led", "cover-letter-professional-founder-led", "ats-cv-fresh-graduate-supervised"],
    backlinks: ["create-professional-cv-for-jobs-sinhala", "linkedin-profile-optimization-sri-lanka", "cv-make-for-interview-calls-sinhala"],
    marketNote: "Targeting younger demographic, pushing the affordable Student Package.",
  },
  {
    slug: "foreign-job-cv-writing-sinhala",
    title: "Foreign Job CV එකක් හදාගන්න",
    subtitle: "විදේශ රැකියා සඳහා ජාත්‍යන්තර ප්‍රමිතීන්ට අනුකූලව ඔබේ CV එක සකසා ගන්න.",
    metaDescription: "යුරෝපය, කැනඩාව, ඔස්ට්‍රේලියාව වැනි රටවල රැකියා සඳහා අයදුම් කිරීමට අවශ්‍ය ජාත්‍යන්තර ප්‍රමිතියේ (International Standard) CV සකස් කිරීම.",
    primaryKeyword: "Foreign Job CV Sinhala",
    secondaryKeywords: ["International standard CV", "overseas job resume", "CV for UK Canada Australia", "විදේශ රැකියා CV"],
    audience: ["යුරෝපීය, කැනඩා හෝ ඔස්ට්‍රේලියානු රැකියා අපේක්ෂිත අය", "Skilled Migration අපේක්ෂා කරන අය"],
    outcomes: ["ජාත්‍යන්තර ATS මෘදුකාංග සඳහා ගැලපීම", "එම රටවලට ආවේණික format (උදා: Canadian / UK Format) භාවිතය", "වීසා සහ රැකියා සම්මුඛ පරීක්ෂණ සඳහා පහසුවීම", "විස්තරාත්මක සහ නිවැරදි වෘත්තීය භාෂාව (English)"],
    relatedPackageSlugs: ["ats-cv-executive-founder-led", "ats-cv-professional-founder-led", "cover-letter-professional-founder-led"],
    backlinks: ["dubai-job-cv-writing-sinhala", "professional-cv-writing-service-sri-lanka-sinhala", "foreign-job-cv-writing-service"],
    marketNote: "Emphasizes international standard formats, primarily English/western markets.",
  },
  {
    slug: "dubai-job-cv-writing-sinhala",
    title: "Dubai Job CV එකක් හදාගන්න",
    subtitle: "ඩුබායි සහ මැදපෙරදිග රැකියා වෙළඳපොල ජයගැනීමට විශේෂයෙන් සකසන ලද Gulf Standard CV එකක්.",
    metaDescription: "ඩුබායි සහ මැදපෙරදිග (Middle East) වැටුප් ඉහළ රැකියා සඳහා විශේෂයෙන් සකසනු ලබන (UAE Format) CV writing සේවාව.",
    primaryKeyword: "Dubai Job CV Sinhala",
    secondaryKeywords: ["Dubai standard CV", "Gulf format resume", "ඩුබායි රැකියා CV", "UAE CV format"],
    audience: ["ඩුබායි රැකියා අපේක්ෂකයින්", "මැදපෙරදිග රටවලට යන අය", "Visit visa මගින් ඩුබායි ගොස් රැකියා සොයන අය"],
    outcomes: ["Gulf කලාපයේ HR සම්මතයන්ට අනුකූල වීම", "කෙටි කාලයකින් අවධානය දිනාගන්නා Executive Summary එකක්", "Dubai ATS ප්‍රමිති සඳහා ගැලපීම", "ඉහළ වැටුප් සහිත රැකියා සඳහා ආරාධනා"],
    relatedPackageSlugs: ["ats-cv-professional-founder-led", "ats-cv-executive-founder-led", "linkedin-professional-founder-led"],
    backlinks: ["foreign-job-cv-writing-sinhala", "dubai-cv-writing-service", "cover-letter-professional-founder-led-writing-sinhala"],
    marketNote: "Specific targeting for the high volume of Sri Lankans going to UAE.",
  },
  {
    slug: "professional-linkedin-profile-optimization-sinhala",
    title: "LinkedIn Profile එක Professional කරගන්න",
    subtitle: "Headhunters සහ Recruiter ලා ඔබව සොයාගෙන එන පරිදි ඔබේ LinkedIn Profile එක සාදා ගන්න.",
    metaDescription: "ඔබේ වෘත්තීය ප්‍රතිරූපය ලොවටම පෙන්වීමට සහ හොඳම රැකියා අවස්ථා ඔබ වෙත ගෙන්වා ගැනීමට LinkedIn Profile එක අවශ‍ය අයුරින් Optimize කරගන්න.",
    primaryKeyword: "LinkedIn Profile Optimization Sinhala",
    secondaryKeywords: ["LinkedIn profile maker Sri lanka", "LinkedIn setup Sinhala", "Professional LinkedIn brand"],
    audience: ["වෘත්තීය දියුණුව අපේක්ෂා කරන අය", "කළමනාකරුවන් සහ විධායක නිලධාරීන්", "Freelancers සහ ව්‍යාපාරිකයින්", "විදේශ රැකියා සොයන අය"],
    outcomes: ["LinkedIn Search Results වල ඉදිරියට පැමිණීම", "Networking අවස්ථා සහ Connection Request වැඩිවීම", "Recruiters ලා හරහා සෘජු රැකියා අවස්ථා ලබාගැනීම", "Personal Brand එක ගොඩනැගීම"],
    relatedPackageSlugs: ["linkedin-student-founder-led", "linkedin-professional-founder-led", "linkedin-executive-founder-led"],
    backlinks: ["professional-cv-writing-service-sri-lanka-sinhala", "foreign-job-cv-writing-sinhala", "cv-review-service-sinhala"],
    marketNote: "Cross-selling the newly added LinkedIn optimization resource/package.",
  },
  {
    slug: "cover-letter-professional-founder-led-writing-sinhala",
    title: "Cover Letter එකක් Professional විදිහට ලියවගන්න",
    subtitle: "CV එකට පමණක් කළ නොහැකි බලපෑමක් ඇතිකරන, රැකියාවටම ගැලපෙන (Tailored) Cover Letter එකක්.",
    metaDescription: "පළමු බැල්මෙන්ම අදාළ රැකියාවට ඔබ සුදුසුම පුද්ගලයා බව සනාථ කරන, කාර්යක්ෂම Cover Letter එකක් ලබාගන්න.",
    primaryKeyword: "Cover Letter Writing Sinhala",
    secondaryKeywords: ["cover letter maker Sri Lanka", "Professional Cover Letter", "Apply letter Sinhala"],
    audience: ["Email හරහා CV යවන අය", "විදේශ රැකියා වලට අපේක්ෂිතයින්", "උසස් මට්ටමේ රැකියා සඳහා apply කරන අය"],
    outcomes: ["CV එක promote කරන අගනා හැඳින්වීමක් ලැබීම", "Keyword Rich content මගින් ATS සමත් වීම", "කෙටි හා පැහැදිලි වෘත්තීය ඉදිරිපත් කිරීම", "අනෙකුත් අපේක්ෂකයින්ගෙන් වෙනස්ව කැපී පෙනීම"],
    relatedPackageSlugs: ["cover-letter-professional-founder-led", "cover-letter-executive-founder-led", "ats-cv-professional-founder-led"],
    backlinks: ["professional-cv-writing-service-sri-lanka-sinhala", "create-professional-cv-for-jobs-sinhala", "cover-letter-writing-service"],
    marketNote: "Emphasizing the value of a cover letter along with a CV.",
  },
  {
    slug: "cv-review-service-sinhala",
    title: "CV එක Review කරගන්න",
    subtitle: "ඔබ දැනටමත් හදාගෙන තියෙන CV එකේ වැරදි සහ අඩුපාඩු හඳුනාගෙන, එය නිවැරදි කරගන්න.",
    metaDescription: "ඔබේ CV එකෙහි ATS ගැටළු, ව්‍යාකරණ දෝෂ, සහ formatting වැරදි තිබේදැයි වෘත්තීය මට්ටමින් පරීක්ෂා කරගැනීමේ සේවාව (CV Review & Audit).",
    primaryKeyword: "CV Review Service Sinhala",
    secondaryKeywords: ["CV checking Sinhala", "CV feedback Sri Lanka", "resume audit", "CV mistakes finder"],
    audience: ["තනිවම CV සකසා ගත් අය", "අලුත්ම Format එකට යාවත්කාලීන වීමට අවශ්‍ය අය", "Interview calls නොලබන අය"],
    outcomes: ["CV එකේ ඇති වැරදි සහ දුර්වලතා පැහැදිලිව හඳුනාගැනීම", "වැඩිදියුණු කලයුතු අංශ පිළිබඳ උපදෙස් කාඩ්පතක්", "ATS යෝග්‍යතාවය (ATS score) පිළිබඳ අදහසක්", "වඩාත් නිවැරදි CV එකකට මගපෙන්වීම"],
    relatedPackageSlugs: ["ats-cv-professional-supervised", "ats-cv-executive-supervised", "ats-cv-professional-founder-led"],
    backlinks: ["cv-make-for-interview-calls-sinhala", "create-ats-friendly-cv-sinhala", "professional-cv-review-service"],
    marketNote: "Low-barrier entry service for those not ready to buy a full write.",
  }
];

export const landingPagesBySlug: Record<string, LandingPage> = Object.fromEntries(
  landingPages.map((item) => [item.slug, item])
);

export function getLandingPageBySlug(slug: string): LandingPage | undefined {
  return landingPagesBySlug[slug];
}
