import { additionalMarketEditorial } from "@/content/additional-market-editorial";
import { newMarketEditorial } from "@/content/new-market-editorial";

export type MarketEditorial = {
  publishedAt?: string;
  intro: string;
  cities: string[];
  sectors: string[];
  keywords: string[];
  focus: string;
  cv: [string, string, string];
  linkedin: [string, string];
  strategy: [string, string];
  headline: string;
  example: string;
  question: string;
  answer: string;
  sources: { title: string; url: string }[];
};

export const marketEditorial: Record<string, MarketEditorial> = {
  ...additionalMarketEditorial,
  ...newMarketEditorial,
  "en-uk": {
    intro: "Your next UK opportunity needs a clear account of what you can contribute. From graduate applications to board-level moves, build a British-English CV, a focused LinkedIn profile and a career story that connects your experience to the role.",
    cities: ["London", "Manchester", "Birmingham", "Edinburgh"],
    sectors: ["Financial services", "Technology", "Professional services", "Operations"],
    keywords: ["UK CV writing service", "professional CV writer UK", "executive CV writing UK", "LinkedIn optimisation UK", "career development UK"],
    focus: "British-English CVs, achievement-led profiles and evidence matched to UK job specifications.",
    cv: [
      "A UK CV should make the connection between your experience and the person specification easy to follow. Start with a short professional profile, then relevant skills, employment and education. Use British spelling consistently, including programme or organisation where appropriate.",
      "For a commercial application, prioritise recent achievements over an exhaustive career history. A concise two-page structure can be a useful starting point, but academic applications and an employer's explicit instructions can call for something different. Remove personal information that does not help establish your suitability.",
      "A Civil Service supporting statement or an employer application form is a separate deliverable from a CV. Collect the criteria and word limits before requesting a quote. The CV can establish your experience; a supporting statement needs evidence that answers the questions being assessed.",
    ],
    linkedin: [
      "Decide whether your UK search is for a functional specialist role, management or consulting. A headline that combines three unrelated ambitions leaves the reader to make that decision. Lead with the role family and add the specialist capabilities that you can support with examples.",
      "For London finance, Manchester technology or a national operations search, give overseas employers a short explanation of their scale and business. Keep location truthful and describe relocation intentions separately. Your About section should explain the next step without publishing confidential client or employer information.",
    ],
    strategy: [
      "Choose a small group of UK vacancies at the same career level and compare the person specifications. Separate capabilities you already demonstrate from experience you need to develop. This produces a more useful application plan than making one CV cover every available role.",
      "Prepare an evidence bank for interviews: a commercial result, a difficult stakeholder situation, a process improvement and a lesson learned. For a public-sector application, match that evidence to the published assessment instructions instead of assuming a commercial CV is sufficient.",
    ],
    headline: "Operations Manager | Service Improvement | Multi-site Team Leadership",
    example: "An operations candidate could replace a list of branch duties with an account of the service issue, the sites involved and the measured improvement, using only verified figures.",
    question: "Can you help with a UK CV and a supporting statement?",
    answer: "The CV is part of the published service. Send the supporting-statement instructions as well; scope, word count and any additional fee are confirmed before that work is accepted.",
    sources: [{ title: "National Careers Service: writing a CV", url: "https://nationalcareers.service.gov.uk/careers-advice/cv-sections" }],
  },
  "en-au": {
    intro: "Make your experience relevant to the Australian role in front of you. Resume writing, LinkedIn optimisation and career strategy connect your achievements to employer requirements, with particular attention to selection criteria and evidence of practical impact.",
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth"],
    sectors: ["Engineering", "Technology", "Resources", "Business services"],
    keywords: ["resume writing Australia", "Australian resume writer", "executive resume Australia", "LinkedIn optimisation Australia", "selection criteria resume"],
    focus: "Australian resumes with clear project evidence and a careful distinction between a resume and selection criteria responses.",
    cv: [
      "Begin with the Australian job advertisement and its required capabilities. A resume should make your relevant experience visible through project scope, achievements and clear dates. Use Australian spelling and explain overseas companies or qualifications without assuming the reader recognises them.",
      "Selection criteria may require separate written responses. Extract each criterion, find a relevant example and record the situation, your actions and the result. Repeating the selection-criteria wording in a skills list does not supply that evidence.",
      "For engineering or resources roles, distinguish the project phase, your discipline, the environment and the work you personally owned. List only current and relevant certifications. Send any additional application requirements for a scope review before choosing a package.",
    ],
    linkedin: [
      "An Australian-facing profile can connect technical expertise with business or project outcomes. A project engineer's headline should identify the discipline and project context, while the About section explains what the candidate can deliver and the teams they work with.",
      "Keep the job titles, dates and employer names on LinkedIn aligned with the resume used for Australian applications. Describe a planned interstate or international move accurately. Use the Featured section for material you have permission to publish, such as a portfolio or a professional presentation.",
    ],
    strategy: [
      "Separate private-sector vacancies from applications with formal selection criteria. Build a schedule that allows time for each required response rather than sending the same attachment everywhere. Compare Sydney, Melbourne, Brisbane and Perth opportunities against your actual role and industry priorities.",
      "For a career transition, identify evidence that transfers: project coordination, safety improvement, client delivery or commercial planning. A consultation can help organise that evidence and prioritise gaps. It cannot substitute for an employer's qualification or eligibility requirements.",
    ],
    headline: "Project Engineer | Infrastructure Delivery | Contractor Coordination",
    example: "An engineering resume can explain the project stage, the interface you managed and the verified delivery result instead of simply listing project names.",
    question: "Are selection criteria included in an Australian resume package?",
    answer: "Separate selection criteria responses are not automatically included. Share the vacancy and response instructions so their scope can be confirmed before payment.",
    sources: [{ title: "SEEK: selection criteria examples", url: "https://au.seek.com/career-advice/article/10-selection-criteria-examples-for-your-resume" }],
  },
  "en-us": {
    intro: "Build a US resume that makes your contribution clear. Position your specialist expertise, leadership scope and business results through concise writing, a consistent LinkedIn presence and a considered strategy for the next stage of your career.",
    cities: ["New York", "San Francisco", "Chicago", "Austin"],
    sectors: ["Technology", "Financial services", "Healthcare operations", "Executive leadership"],
    keywords: ["resume writing services USA", "professional resume writer US", "executive resume writing", "LinkedIn profile optimization USA", "US career strategy"],
    focus: "US resumes that connect the target title to measurable contributions and a consistent executive narrative.",
    cv: [
      "For a US private-sector search, use resume language and a concise account of relevant experience. Academic CVs and specialist application formats serve different purposes. Confirm the type of application before deciding how much career history belongs in the document.",
      "Translate responsibilities into contributions: the product you helped deliver, the process you improved or the revenue you can substantiate. If a figure is confidential, describe the scale in an approved way. Do not fabricate metrics to make an achievement look more impressive.",
      "A technology resume should distinguish hands-on depth from team leadership. A director or executive resume should make decision-making scope visible. Avoid treating a list of software tools as a substitute for evidence of how those tools supported the work.",
    ],
    linkedin: [
      "Choose the US role family you want to be associated with before rewriting your headline. Product management, program management and project management are related but different searches. Use the title that accurately fits your experience and target direction.",
      "Your About section can connect a career transition more naturally than a resume summary. Explain the problem space you work in, a few representative contributions and the kinds of responsibilities you want next. Maintain consistency across dates and leadership claims.",
    ],
    strategy: [
      "Build a target-company list around role scope, not brand recognition alone. Compare whether a director title means individual expertise, people management or ownership of a business function. This helps avoid applying at the wrong level across different US companies.",
      "Use a weekly review of applications, conversations and interview feedback to refine the strategy. A career consultation can clarify positioning and priorities. Federal, academic and other specialist applications should be scoped separately against the vacancy instructions.",
    ],
    headline: "Product Leader | B2B SaaS | Customer Discovery & Product Strategy",
    example: "A product leader can show the customer problem, decisions owned and adoption evidence rather than using a string of generic leadership adjectives.",
    question: "Is this service for US resumes or academic CVs?",
    answer: "The standard service supports professional and executive resumes. Share academic, federal or other specialist requirements before booking so suitability and scope can be assessed.",
    sources: [{ title: "CareerOneStop: resumes", url: "https://www.careeronestop.org/JobSearch/Resumes/Resumes.aspx" }],
  },
  "en-ca": {
    intro: "Present your experience clearly for Canadian opportunities, including when your career was built overseas. A focused resume and LinkedIn profile help connect your achievements to the role without losing the substance of your previous work.",
    cities: ["Toronto", "Vancouver", "Calgary", "Ottawa"],
    sectors: ["Technology", "Finance", "Engineering", "Operations"],
    keywords: ["Canada resume writing", "Canadian resume format", "resume writer Canada", "LinkedIn optimization Canada", "newcomer resume Canada"],
    focus: "Canadian resumes that explain transferable experience, employer context and role relevance without overstating local experience.",
    cv: [
      "A Canadian resume should be tailored to the position and easy to scan. Job Bank recommends a clear presentation of relevant experience and accomplishments. Avoid including a photograph or unnecessary personal information in a standard professional resume.",
      "If your experience comes from outside Canada, explain unfamiliar employer names with a brief industry or scale description. Show the systems you used, the decisions you made and the people or customers affected. Do not relabel overseas work as Canadian experience.",
      "List qualifications exactly as awarded. A credential assessment or professional registration is a separate matter from resume writing. Include its verified status only when relevant, and follow the employer's application instructions for documents and language.",
    ],
    linkedin: [
      "For a Canadian search, an effective profile can bridge unfamiliar company names and recognisable responsibilities. Explain the business context in the Experience section and use accurate functional titles. Avoid changing titles just to match a vacancy.",
      "Toronto finance, Vancouver technology and Calgary project searches may need different evidence. Choose the direction you actually want and reflect it in your headline. Keep your present location accurate and explain relocation plans clearly in the appropriate profile fields or conversations.",
    ],
    strategy: [
      "Map the Canadian vacancies you are considering against demonstrated skills, sector familiarity and any employer-stated credentials. This separates a writing problem from a qualification gap and helps you direct effort where your experience is most relevant.",
      "Prepare concise explanations of overseas achievements for recruiter conversations. Keep an application record by city, role and feedback so you can distinguish a weak target list from a weak document. Resume support does not determine immigration or professional registration outcomes.",
    ],
    headline: "Business Analyst | Financial Services | Process Improvement & Reporting",
    example: "A newcomer business analyst can explain the organisation's scale and the reporting problem solved without implying Canadian employment history.",
    question: "Can you adapt overseas experience to a Canadian resume?",
    answer: "Yes. The writing explains your experience in relevant, accessible terms while keeping employers, qualifications, locations and achievements accurate.",
    sources: [{ title: "Government of Canada Job Bank: writing a good resume", url: "https://www.jobbank.gc.ca/findajob/resources/write-good-resume" }],
  },
  "en-nz": {
    intro: "Give New Zealand employers a practical account of your strengths. CV writing, LinkedIn optimisation and career consultation help connect overseas or local experience to the responsibilities of your next role.",
    cities: ["Auckland", "Wellington", "Christchurch", "Hamilton"],
    sectors: ["Engineering", "Business services", "Technology", "Logistics"],
    keywords: ["CV writing New Zealand", "professional CV writer NZ", "New Zealand CV format", "LinkedIn optimisation NZ", "career consultation NZ"],
    focus: "Practical New Zealand CVs that balance relevant work history, transferable skills and clear supporting examples.",
    cv: [
      "Select a CV structure that makes your strongest evidence easy to find. A work-focused CV suits a direct progression, while a career change may need a clearer skills section supported by examples. Keep your employment history visible rather than hiding gaps in a purely functional format.",
      "For New Zealand applications, describe your contribution in straightforward language. Explain what you did, who benefited and what changed. If your previous employers are unfamiliar to the reader, a brief description is more useful than promotional language about the company.",
      "Prepare referee information separately and ask permission before sharing contact details. Check whether the employer wants a cover letter, an application form or a particular file type. The vacancy instructions take priority over a generic template.",
    ],
    linkedin: [
      "A New Zealand-facing profile can show both specialist skills and the breadth of responsibility you have held. For a smaller employer, explain how you worked across teams rather than assuming a narrow job title conveys that experience.",
      "Keep LinkedIn and your CV aligned when approaching Auckland, Wellington or regional employers. Use the About section to explain the work you want next and how earlier experience transfers. A truthful statement about location and availability prevents confusion later.",
    ],
    strategy: [
      "Compare the scope of the role as well as the title when moving into the New Zealand market. Identify the responsibilities you can already support with evidence and those that require a more focused development plan.",
      "Build a short set of interview examples around collaboration, practical problem solving and delivery. A consultation can organise the search by role and location, while each employer remains responsible for deciding suitability and eligibility.",
    ],
    headline: "Supply Chain Specialist | Inventory Planning | Distribution Operations",
    example: "A logistics candidate could describe an inventory problem, their coordination with suppliers and the verified service improvement.",
    question: "Do you support candidates moving to New Zealand?",
    answer: "Yes. CV and profile writing can explain transferable experience and your intended career direction. It is separate from visa, registration or migration advice.",
    sources: [{ title: "Careers New Zealand: CVs and cover letters", url: "https://www.careers.govt.nz/how-to-get-a-job/cvs-and-cover-letters/" }],
  },
  "en-ae": {
    intro: "Make your experience clear for opportunities in Dubai, Abu Dhabi and the wider UAE. Present the scope of your work, the sectors you understand and the value you bring through an ATS-friendly CV and a coherent professional profile.",
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
    sectors: ["Construction", "Financial services", "Hospitality", "Logistics"],
    keywords: ["CV writing UAE", "CV writing Dubai", "professional CV writer Abu Dhabi", "LinkedIn optimization UAE", "executive CV UAE"],
    focus: "English UAE CVs with clear project scope, accurate availability and relevant GCC or international experience.",
    cv: [
      "A UAE CV should establish the role you are targeting before listing everything you have ever done. A construction project manager and an operations manager need different evidence even when both have managed people and budgets. Select the experience that best supports the vacancy.",
      "Make project scale and personal responsibility explicit. Distinguish the employer, the client and the project where that is useful and permitted. GCC experience should be identified accurately; overseas experience should be explained through transferable capability rather than disguised as regional experience.",
      "Follow the employer's instructions on application information. State availability or notice period accurately when requested. Do not assume that a photograph, passport details or sensitive personal data belong in every UAE CV; requirements vary by organisation and application channel.",
    ],
    linkedin: [
      "For a Dubai or Abu Dhabi search, lead with an accurate professional identity and sector specialism. A profile that says only 'seeking opportunities in UAE' gives a recruiter little evidence of fit. Show the discipline and type of work you can undertake.",
      "Use the Experience section to explain regional projects and international responsibilities separately. Update location and availability honestly. LinkedIn optimisation here means content and positioning support; you retain control of the account and no password is needed.",
    ],
    strategy: [
      "Separate your target employers by sector and role scope before applying. A hospitality operations search requires different examples from a logistics or construction search, even when the applicant is considering all three in the UAE.",
      "Prepare a concise explanation of your recent work, availability and intended role for recruiter conversations. Track which channels produce relevant discussions. Application writing can improve presentation, but it does not guarantee employment or any visa decision.",
    ],
    headline: "Construction Project Manager | Commercial Fit-Out | Project Delivery",
    example: "A project manager can name the project type, phases owned and coordination responsibilities without publishing a confidential client budget.",
    question: "Do all UAE CVs need a photo or visa details?",
    answer: "No single format fits every employer. Share the vacancy instructions so relevant information can be included without adding unnecessary sensitive data.",
    sources: [{ title: "Labeeb: UAE LinkedIn profile service", url: "https://labeeb.ae/linkedin-profile-optimization/" }],
  },
  "en-sa": {
    intro: "Build a focused career story for Saudi Arabian opportunities. English CV writing and LinkedIn positioning help specialists and leaders explain project delivery, technical expertise and organisational impact for their chosen employer.",
    cities: ["Riyadh", "Jeddah", "Dammam", "Khobar"],
    sectors: ["Engineering", "Technology", "Construction", "Business transformation"],
    keywords: ["CV writing Saudi Arabia", "professional CV writer KSA", "Riyadh CV writing", "LinkedIn optimization Saudi Arabia", "executive CV KSA"],
    focus: "Saudi-targeted English CVs that distinguish discipline, project responsibility and evidence of delivery.",
    cv: [
      "For a Saudi Arabian application, begin with the actual project or business need in the vacancy. Broad statements about supporting transformation are less informative than evidence of the systems, teams or delivery stages you have managed.",
      "Technical candidates should separate qualifications, tools and applied experience. An engineering certificate is not evidence that you led an engineering team; a team title is not evidence of hands-on technical depth. Make the distinction easy for the reader to assess.",
      "Use consistent English titles and explain local acronyms when your experience spans countries. If the employer requests an Arabic document or a specific portal format, identify that before commissioning the work. The standard service on this section is English-language writing.",
    ],
    linkedin: [
      "A Riyadh transformation profile should identify the function being transformed: finance, technology, operations or customer service. Build the headline around verified experience instead of using national programme language as a substitute for a professional specialism.",
      "Describe the responsibilities you actually owned on large programmes. Explain stakeholders, implementation phases and outcomes without implying authority over the whole programme. This makes the LinkedIn narrative consistent with the evidence in your CV.",
    ],
    strategy: [
      "Group Saudi opportunities by employer, sector and level of responsibility. Compare the advertised requirements to your own evidence before investing time in a full application. An attractive project name alone is not enough to establish role fit.",
      "Use career consultation to clarify which experiences best support the target role and which gaps need development. Confirm language and application requirements directly with the employer. Service availability and payment details are reviewed before an engagement begins.",
    ],
    headline: "Programme Manager | Business Transformation | Implementation & Governance",
    example: "A transformation candidate can explain the business function, rollout stage and decisions owned instead of claiming to have delivered an entire national programme.",
    question: "Does the Saudi service include Arabic translation?",
    answer: "These packages provide English documents. Any Arabic or bilingual requirement must be discussed and confirmed separately before work begins.",
    sources: [{ title: "OxfordCV: Saudi Arabia career document services", url: "https://oxfordcv.com/" }],
  },
  "en-mv": {
    intro: "Turn resort, hospitality or business experience into a focused professional CV for Maldives opportunities. Show the responsibilities behind your job title, the standards you worked to and the contribution you can bring to your next team.",
    cities: ["Male", "Hulhumale", "Addu", "Resort islands"],
    sectors: ["Hospitality", "Resort operations", "Finance", "Guest services"],
    keywords: ["CV writing Maldives", "hospitality CV Maldives", "resort CV writing", "LinkedIn optimization Maldives", "career consultation Maldives"],
    focus: "Hospitality and professional CVs that show service standards, operating context and practical achievements.",
    cv: [
      "A Maldives hospitality CV should explain the setting in which you worked. State the department, property type and level of responsibility so the reader can understand your experience. A title such as supervisor means more when the team and operation are clear.",
      "For guest-facing work, describe the service problems you solved and how you worked with other departments. For commercial or finance roles, show the controls, reporting or planning responsibilities you owned. Use only figures and guest information you are authorised to disclose.",
      "Include languages with an honest description of proficiency, relevant training and clear employment dates. Keep a separate record of references or certificates requested by an employer. Do not upload personal identity documents unless the application process legitimately requires them.",
    ],
    linkedin: [
      "A professional profile can show how resort experience transfers across properties and brands. Explain service leadership, operational coordination or commercial expertise rather than making the profile a list of resorts.",
      "For a Maldives or wider international hospitality search, keep your experience and language claims consistent with your CV. A headline can name the discipline and specialism. Never publish guest details, internal occupancy reports or confidential employer data as portfolio evidence.",
    ],
    strategy: [
      "Decide whether the next step is a larger property, a new department or a leadership role. Each route needs different evidence. A move from guest services to operations management should show coordination and decision-making as well as service experience.",
      "Prepare examples of complaint resolution, team training and collaboration across departments. Review vacancy instructions and keep certificates ready when requested. Career writing helps present experience; the employer assesses fit and makes the hiring decision.",
    ],
    headline: "Hospitality Professional | Guest Experience | Resort Operations",
    example: "A front-office supervisor can describe how a handover improvement reduced repeat guest issues, with a verified outcome and no guest-identifying details.",
    question: "Can you write a CV for Maldives resort jobs?",
    answer: "Yes. Share the department, target position, relevant property experience and vacancy so the document can focus on the operational and service evidence that matters.",
    sources: [{ title: "Maldives National Careers Service", url: "https://mycareer.gov.mv/en/employers/national-careers-service" }],
  },
  "en-sg": {
    intro: "Position your expertise for Singapore employers and regional leadership roles. A precise resume, recruiter-facing LinkedIn profile and focused career strategy help explain both specialist depth and responsibility across markets.",
    cities: ["Singapore", "Central Business District", "Jurong", "Changi"],
    sectors: ["Financial services", "Technology", "Regional operations", "Supply chain"],
    keywords: ["resume writing Singapore", "professional CV writer Singapore", "LinkedIn optimisation Singapore", "executive resume Singapore", "career development Singapore"],
    focus: "Singapore resumes that distinguish local delivery from APAC responsibilities and connect skills to business outcomes.",
    cv: [
      "For a Singapore resume, distinguish your functional expertise from the geographical scope of your work. If a role covered APAC, explain which responsibilities were regional and which were specific to one office or country.",
      "A skills section should support the target role with recognisable tools and capabilities. Back it with employment examples. For finance or technology applications, clarify the product, system or operating environment rather than assuming the employer can infer it from your title.",
      "Keep a clear separation between resume content and the application information an employer requests. State qualifications and employment details accurately, and check language and document requirements for each vacancy. Writing support does not establish work-pass eligibility.",
    ],
    linkedin: [
      "If you are targeting Singapore-based regional roles, make the APAC scope of your work precise. Name the coordination or delivery responsibility you owned rather than presenting occasional cross-border meetings as regional leadership.",
      "An effective About section links specialist knowledge to the business issue it helps solve. Keep the profile readable for both recruiters and functional leaders. Update your role preferences and location honestly, and use a headline that matches the actual level you are pursuing.",
    ],
    strategy: [
      "Compare a Singapore individual-contributor role with a regional role before deciding how to position yourself. Team size, decision rights and market coverage can differ significantly behind similar titles. Use the vacancy's responsibilities as the reference point.",
      "Build evidence for stakeholder management across functions and markets, then identify any missing technical or leadership depth. A consultation can prioritise the next step and application sequence without promising employer responses.",
    ],
    headline: "Regional Finance Manager | APAC Reporting | Business Partnering",
    example: "A regional finance candidate can explain the reporting cycle, markets supported and decisions enabled without claiming ownership of all APAC finance operations.",
    question: "Can you support a Singapore-based APAC leadership application?",
    answer: "Yes. The review distinguishes regional scope, functional ownership and leadership evidence so the resume and LinkedIn profile reflect your actual responsibilities.",
    sources: [{ title: "ResumeWriter Singapore: career document services", url: "https://www.resumewriter.sg/" }],
  },
  "en-my": {
    intro: "Build a resume for the Malaysian opportunity you want next. Connect technical knowledge, commercial results and cross-functional experience through clear English writing, LinkedIn positioning and a practical career plan.",
    cities: ["Kuala Lumpur", "Penang", "Johor Bahru", "Cyberjaya"],
    sectors: ["Manufacturing", "Technology", "Shared services", "Finance"],
    keywords: ["resume writing Malaysia", "professional resume writer Malaysia", "LinkedIn optimisation Malaysia", "English CV Malaysia", "career strategy Malaysia"],
    focus: "Malaysian resumes that explain technical depth, shared-service responsibilities and language capabilities accurately.",
    cv: [
      "A Malaysian resume should connect your experience to the specific job family. Manufacturing, shared services and software roles need different examples. Start with the capabilities in the advertisement and choose achievements that demonstrate them.",
      "For manufacturing or engineering, identify the process, equipment or quality responsibility you handled. For shared services, explain the function, stakeholders and scope of service. Use a simple structure that gives the reader both context and results.",
      "List language skills accurately and distinguish working proficiency from conversational knowledge. Keep the job titles and dates consistent with your application profiles. An English resume can support suitable roles, but the employer's requested language remains the starting point.",
    ],
    linkedin: [
      "Choose a professional headline that reflects your Malaysian target role and strongest capability. A specialist in finance shared services can name reporting, controls or process improvement rather than trying to appear suitable for every corporate function.",
      "Align LinkedIn with the resume and any job-platform profile you maintain. The wording need not be identical, but employer names, dates and achievements should agree. Highlight work with regional stakeholders where you can explain your own contribution clearly.",
    ],
    strategy: [
      "Compare opportunities across Kuala Lumpur, Penang and Johor by role and industry rather than location alone. Assess whether the next move is a specialist promotion, a people-management step or a change of sector.",
      "Prepare evidence of collaboration, process reliability and technical learning. Review applications for patterns in the requirements you are missing. A career session can help decide which gaps require a better explanation and which need practical development.",
    ],
    headline: "Finance Shared Services Specialist | Reporting | Process Improvement",
    example: "A shared-services professional can describe the reporting workflow improved, teams supported and verified reduction in rework.",
    question: "Will the Malaysia resume and LinkedIn profile use the same positioning?",
    answer: "Yes. Both are aligned to your chosen role and level, while LinkedIn allows a more conversational explanation of your professional direction.",
    sources: [{ title: "Jobstreet Malaysia: resume guidance", url: "https://my.jobstreet.com/career-advice/article/resume-template" }],
  },
  "en-ru": {
    intro: "Translate the substance of your career into clear English for Russia-linked and international opportunities. CV writing and career strategy help explain technical expertise, unfamiliar titles and overseas ambitions with accurate, readable evidence.",
    cities: ["Moscow", "Saint Petersburg", "Kazan", "International remote roles"],
    sectors: ["Software engineering", "Data", "Technical consulting", "Product management"],
    keywords: ["English CV writing Russia", "English resume Russia", "international CV for Russian professionals", "career strategy Russia", "international LinkedIn profile writing"],
    focus: "English career documents that explain Russian experience to international readers without relying on literal translation.",
    cv: [
      "An English CV for a Russia-linked international search needs more than a literal translation. Explain the purpose of your role, the employer's business and the work you owned. Translate specialist terms for the reader while keeping the original qualification or title clear where needed.",
      "Technical candidates should connect a technology stack to real delivery: the system built, the reliability problem addressed or the process improved. Do not include internal architecture details or confidential data simply to make the project description look more substantial.",
      "Decide whether the target employer wants an English resume, a longer CV or a platform profile. Keep dates and company information consistent across versions. These packages provide English writing; Russian translation and platform-specific work require separate confirmation.",
    ],
    linkedin: [
      "For an international-facing profile, write a headline that explains your role without local abbreviations. Product, engineering and data responsibilities should be recognisable to the employer you are targeting. Avoid translating a title into a higher seniority level than you held.",
      "Use a professional profile only where the platform is available and appropriate to your search. Do not make LinkedIn the sole application channel. An English CV, portfolio and direct employer application can carry the same consistent professional story.",
    ],
    strategy: [
      "Begin with a realistic shortlist of employers, languages and working arrangements. Check the employer's current ability to engage candidates in your circumstances directly before investing in a long application process.",
      "A consultation can help translate career experience into a clear direction and evidence plan. Service availability and supported payment arrangements are confirmed individually before booking; a displayed RUB estimate does not promise a particular payment provider.",
    ],
    headline: "Software Engineer | Backend Systems | Reliability & Performance",
    example: "An engineer can explain the user-facing purpose of a system and the reliability work they owned without publishing proprietary implementation details.",
    question: "Does RUB pricing mean every international payment method is available?",
    answer: "No. RUB is a reference estimate. Service availability, invoice currency and supported payment arrangements are confirmed before an engagement is accepted.",
    sources: [{ title: "HeadHunter: an English resume is more than a translation", url: "https://hh.ru/article/24592" }],
  },
  "en-qa": {
    intro: "Present a clear professional case for opportunities in Qatar. CV writing, LinkedIn positioning and career strategy help specialists and executives show project experience, operational responsibility and the outcomes they can substantiate.",
    cities: ["Doha", "Lusail", "Al Wakrah", "Ras Laffan"],
    sectors: ["Energy", "Engineering", "Hospitality", "Facilities management"],
    keywords: ["CV writing Qatar", "professional CV writer Doha", "LinkedIn optimization Qatar", "executive CV Qatar", "Qatar career consultation"],
    focus: "Qatar CVs that make technical discipline, project setting and operational contribution easy to assess.",
    cv: [
      "For a Qatar application, specify the discipline and context behind your experience. Energy, facilities and hospitality employers need different evidence. A general Gulf CV can miss the responsibilities of the actual role you are pursuing.",
      "Explain whether you worked for a client, contractor or service provider, where disclosure is permitted. Distinguish construction, commissioning, maintenance and ongoing operations. This gives the reader a clearer picture than a list of project names alone.",
      "List training, qualifications and availability accurately. Check the employer's requirements before adding photos or personal status information. Never imply a local licence, approval or authorisation that you do not hold.",
    ],
    linkedin: [
      "A Doha-facing profile should state the professional discipline first. For a facilities manager, describe the type of assets, service responsibilities and team interfaces rather than using broad claims about operational excellence.",
      "Keep regional project experience consistent with the CV and avoid suggesting ownership of an entire development when you managed one workstream. A credible profile makes boundaries clear and connects your work to the results you can explain in an interview.",
    ],
    strategy: [
      "Choose a target role and project environment before selecting employers in Qatar. A move between energy projects and facilities operations may require a different account of the same technical background.",
      "Build an evidence bank around reliability, coordination, delivery and stakeholder management. Ask for feedback on role fit as well as writing quality. Career document support is separate from any employer's eligibility or recruitment decisions.",
    ],
    headline: "Facilities Manager | Asset Operations | Service Delivery & Maintenance",
    example: "A facilities candidate can describe the assets supported, the maintenance coordination challenge and the verified service result.",
    question: "Can you tailor a Qatar CV to an energy or facilities role?",
    answer: "Yes. Share the vacancy and project context so the writing can distinguish technical discipline, delivery stage and your personal responsibility.",
    sources: [{ title: "CVBee: GCC CV and profile writing", url: "https://cvbee.me/" }],
  },
  "en-om": {
    intro: "Build an English CV that makes your experience relevant to Oman employers. Clarify the work you own, the environments you understand and the value you can contribute in technical, commercial or leadership roles.",
    cities: ["Muscat", "Sohar", "Salalah", "Duqm"],
    sectors: ["Energy", "Logistics", "Industrial projects", "Tourism"],
    keywords: ["CV writing Oman", "professional CV writer Muscat", "LinkedIn optimization Oman", "Oman CV format", "career strategy Oman"],
    focus: "Oman-targeted CVs with precise operational context and an accurate account of experience across projects and employers.",
    cv: [
      "For an Oman CV, connect the role to the setting in which you worked. Port logistics, industrial operations and tourism involve different responsibilities. Explain the operating environment before describing the achievements most relevant to the vacancy.",
      "A technical or project CV should show your discipline, the work packages you owned and the interfaces you coordinated. Keep client and contractor relationships clear. Relevant experience from another country can be valuable without being presented as Oman-based experience.",
      "Follow the employer's instructions on language, certificates and application fields. Do not add eligibility claims based on a generic template. English document writing does not determine suitability under an employer's recruitment requirements.",
    ],
    linkedin: [
      "A profile targeting Muscat or an industrial hub should connect the role title with a clear specialism. Logistics planning, procurement and warehouse operations are distinct capabilities; choose the ones you can support with recent examples.",
      "Use the About section to explain how you work across contractors, suppliers or internal departments. Keep information about location and availability current. The professional story should remain consistent when an employer compares LinkedIn with your CV.",
    ],
    strategy: [
      "Compare the role requirements across Muscat, Sohar, Salalah and Duqm before widening an application campaign. Location alone does not establish fit; project stage and operational setting may matter more to your next step.",
      "A career session can help decide whether your strongest route is deeper technical work, operations leadership or a sector transition. Build the application around evidence of that direction and confirm employer-specific requirements directly.",
    ],
    headline: "Logistics Coordinator | Port Operations | Supplier & Transport Planning",
    example: "A logistics candidate can describe the planning responsibility, coordination challenge and delivery outcome without claiming control of a whole port operation.",
    question: "Can the same CV cover Oman logistics and tourism jobs?",
    answer: "Some transferable experience may overlap, but separate role-focused versions are usually clearer. The review identifies which evidence and scope each application needs.",
    sources: [{ title: "CV Gulf: Oman CV services", url: "https://www.cvgulf.com/oman" }],
  },
  "en-kw": {
    intro: "Present your experience clearly for Kuwait roles in engineering, business and leadership. Premium CV writing and profile positioning focus on the evidence behind your title, with career strategy shaped around your intended next step.",
    cities: ["Kuwait City", "Ahmadi", "Salmiya", "Farwaniya"],
    sectors: ["Energy", "Banking", "Engineering", "Retail operations"],
    keywords: ["CV writing Kuwait", "Kuwait CV writer", "LinkedIn optimization Kuwait", "executive CV Kuwait", "Kuwait career guidance"],
    focus: "Kuwait CVs that make the relationship between technical expertise, commercial responsibility and team leadership explicit.",
    cv: [
      "A Kuwait application should make the relevant sector experience easy to assess. Banking controls, engineering delivery and retail operations need different achievement examples. Start with the vacancy rather than a single all-purpose Gulf document.",
      "For an engineering CV, state the project environment and work you personally delivered. For a banking or commercial CV, explain the function, controls or client responsibilities without disclosing restricted information. Keep the scale of your claims proportionate to your role.",
      "Check application requirements before adding photos, identity details or personal status information. Use truthful qualification names and current certification details. If a document needs another language or specialist format, confirm that scope in advance.",
    ],
    linkedin: [
      "For a Kuwait-facing profile, a concise headline can connect your job family with specialist expertise. 'Finance professional' is broad; a truthful combination such as financial control and reporting gives a reader more to work with.",
      "Explain transitions between sectors in the About section using transferable responsibilities and evidence. Keep career dates aligned with the CV. A profile should support recruiter conversations without promising visibility or responses from particular employers.",
    ],
    strategy: [
      "Choose the level and scope of the Kuwait roles you want before revising your documents. A branch leadership role, regional operations role and specialist finance role may use overlapping language but require different evidence.",
      "Use a consultation to identify which achievements show readiness for the next step. Build a short application list and prepare examples of judgment, delivery and collaboration. Confirm employer requirements and engagement details before committing to a process.",
    ],
    headline: "Financial Controller | Reporting & Controls | Business Performance",
    example: "A finance candidate can explain a control improvement and their role in its implementation while keeping confidential account data private.",
    question: "Why are Kuwait prices displayed with three decimal places?",
    answer: "Kuwaiti dinar amounts use three-decimal currency formatting. These are reference conversions; the final invoice amount and currency are confirmed before payment.",
    sources: [{ title: "BrandMyProfile: Kuwait and GCC career services", url: "https://www.brandmyprofile.com/" }],
  },
  "en-ie": {
    intro: "Build a CV for your next Irish opportunity with a clear professional profile and relevant evidence. Resume your career story around the role you want, supported by LinkedIn optimisation and personal guidance on positioning.",
    cities: ["Dublin", "Cork", "Galway", "Limerick"],
    sectors: ["Technology", "Life sciences", "Financial services", "Business operations"],
    keywords: ["CV writing Ireland", "professional CV writer Dublin", "LinkedIn optimisation Ireland", "executive CV Ireland", "career consultation Ireland"],
    focus: "Irish-market CVs that connect relevant experience with the employer's role requirements and a coherent professional profile.",
    cv: [
      "An Irish CV should establish your fit for the specific opportunity. Begin with a short professional profile and recent relevant achievements, then use employment and education sections that are easy to follow. Keep spelling and terminology consistent throughout.",
      "For technology or life-sciences roles, explain the product, process or environment in which you worked. Distinguish specialist contribution from people management. List relevant qualifications accurately rather than implying recognition or registration that has not been confirmed.",
      "A concise commercial CV and a research or academic CV have different purposes. Read the employer's instructions before choosing the length and format. A cover letter should add a role-specific explanation rather than repeat the whole CV.",
    ],
    linkedin: [
      "For an Ireland-facing profile, connect the headline to a recognisable specialism and professional direction. A Dublin finance search and a Cork life-sciences search require different evidence even when both involve project or team leadership.",
      "Use the About section to explain your contribution and the type of problem you solve. Keep LinkedIn aligned with the CV so recruiters see consistent dates, employers and responsibility. Include relevant professional material only when you have permission to share it.",
    ],
    strategy: [
      "Compare target employers by work scope and sector before deciding whether to apply nationally or concentrate on one city. Your strongest evidence may fit one role family much better than a broad category of management jobs.",
      "Prepare examples that demonstrate the capabilities in the Irish vacancy, including collaboration and practical delivery. A career consultation can prioritise applications and development gaps without promising a hiring outcome.",
    ],
    headline: "Quality Professional | Life Sciences | Process Improvement & Documentation",
    example: "A quality candidate can describe the process reviewed, the documentation improved and the verified operational benefit.",
    question: "Is an Irish CV different from an academic CV?",
    answer: "The format depends on the purpose. Standard packages focus on professional applications; send research or academic instructions for a suitability and scope review.",
    sources: [{ title: "Leap Coaching: LinkedIn profiles for Irish recruiters", url: "https://leapcoaching.ie/how-to-optimise-your-linkedin-profile-for-recruiters-in-ireland/" }],
  },
  "en-fi": {
    intro: "Make your skills and work experience clear for English-language opportunities in Finland. A focused CV, honest language profile and practical career strategy help employers understand how your background relates to their work.",
    cities: ["Helsinki", "Espoo", "Tampere", "Turku"],
    sectors: ["Software", "Engineering", "Research", "Product development"],
    keywords: ["English CV writing Finland", "CV writer Finland", "Finnish job market CV", "LinkedIn optimisation Finland", "career coaching English Finland"],
    focus: "English CVs for Finland with concrete skills evidence, clear language proficiency and employer-specific relevance.",
    cv: [
      "For a Finland application, identify the skills and experience that answer the employer's needs. Present your competence through concrete work, projects or studies. Keep the CV focused on the role instead of treating it as a complete personal history.",
      "Describe language proficiency honestly and follow the vacancy's requested application language. An English CV is useful for suitable English-language roles, but it does not remove a Finnish or Swedish requirement where an employer specifies one.",
      "If your work experience is from another country, explain the context in plain terms and show the relevant contribution. Projects or portfolio links can help demonstrate technical work when they are public and appropriate to share. Confirm academic formats separately.",
    ],
    linkedin: [
      "A Finland-facing profile can make specialist skills discoverable while keeping the narrative practical. Explain your technical area, the work you enjoy and the contribution you have made. Avoid a headline made entirely from aspirational titles.",
      "Use the Experience and Projects sections to connect claims to concrete work. Keep language skills and location accurate. Your LinkedIn account remains yours; the service supplies writing and recommendations rather than requesting login credentials.",
    ],
    strategy: [
      "Start with vacancies where your skills and language capabilities match the stated requirements. Compare whether the employer needs a specialist, a researcher or a generalist contributor. This helps focus a Finland search before rewriting every application.",
      "Build a small portfolio of examples and a plan for professional conversations. A consultation can clarify how existing experience transfers and what needs development. Networking and a polished CV support the search but cannot guarantee an offer.",
    ],
    headline: "Software Developer | Cloud Services | Reliable Product Delivery",
    example: "A developer can explain a publicly shareable project, the problem it solved and the technical decisions they owned.",
    question: "Can I use an English CV to apply in Finland?",
    answer: "Use the language requested in the vacancy. This service supports English documents and does not replace Finnish or Swedish proficiency where the employer requires it.",
    sources: [{ title: "InfoFinland: job application and CV", url: "https://infofinland.fi/en/work-and-enterprise/find-a-job-in-finland/job-application-and-cv" }],
  },
  "en-in": {
    intro: "Present your expertise for Indian employers, multinational teams and international career moves. A focused resume and LinkedIn profile help specialists and senior leaders communicate depth, delivery and the scope of their next role.",
    cities: ["Bengaluru", "Mumbai", "Hyderabad", "Delhi NCR"],
    sectors: ["Technology", "Financial services", "Consulting", "Global capability centres"],
    keywords: ["resume writing India", "executive resume writer India", "LinkedIn profile optimization India", "ATS resume India", "career development India"],
    focus: "Indian professional resumes that connect skills to delivery and make seniority, client work and leadership scope explicit.",
    cv: [
      "For an India resume, align the professional summary with a specific role family. A long inventory of tools and training can hide the work you are best qualified to do. Prioritise the capabilities in the vacancy and substantiate them in the employment section.",
      "For technology or consulting, distinguish your employer from the client project where disclosure is permitted. Explain the business problem, your responsibility and the result. Make individual contribution and management responsibility clear rather than combining them into one inflated claim.",
      "For leadership applications, describe team scope, stakeholder responsibility and decisions owned. Keep career dates consistent with application portals and LinkedIn. Use only accurate qualifications, tools and achievements, even when a keyword appears repeatedly in advertisements.",
    ],
    linkedin: [
      "A strong India-facing profile starts with a precise professional identity. If you are targeting a global capability centre or product company, explain how your experience fits that operating context rather than using a headline full of unrelated technologies.",
      "Keep the professional narrative consistent across LinkedIn, your resume and job-platform profiles. Exact job titles and dates should agree. You can explain the desired next step in the About section without presenting an aspiration as experience already earned.",
    ],
    strategy: [
      "Decide whether the next move is into specialist depth, people leadership or a different employer model. A services-to-product transition may need stronger evidence of product decisions, while a leadership move needs evidence of judgment and ownership.",
      "Use representative vacancies from Bengaluru, Hyderabad, Mumbai or your intended location to identify recurring requirements. A consultation helps prioritise experience and development gaps. It does not replace the work needed to build a missing skill.",
    ],
    headline: "Engineering Manager | Product Development | Team Leadership & Delivery",
    example: "A technology leader can describe the delivery responsibility and team decisions they owned rather than listing every framework used across the company.",
    question: "Can you align my resume with LinkedIn and job-portal applications?",
    answer: "Yes. The documents can share a consistent role direction and evidence. Direct portal editing or account management is not automatically included and must be scoped separately.",
    sources: [{ title: "Get Set Resumes: India resume and career services", url: "https://www.getsetresumes.com/" }],
  },
  "en-bd": {
    intro: "Build a clear English CV for Bangladesh-based employers and international opportunities. Present your achievements, sector knowledge and career direction through professional writing and a consistent online profile.",
    cities: ["Dhaka", "Chattogram", "Sylhet", "Remote teams"],
    sectors: ["Technology", "Banking", "Apparel operations", "Development organisations"],
    keywords: ["CV writing Bangladesh", "professional CV writer Dhaka", "LinkedIn optimization Bangladesh", "English resume Bangladesh", "international CV Bangladesh"],
    focus: "English CVs that distinguish professional applications from other biodata formats and explain achievements for local or overseas employers.",
    cv: [
      "A professional Bangladesh CV should be built around the role and employer. Banking, technology, apparel and development-sector applications need different evidence. Avoid using a general biodata document when the employer needs a clear account of professional capabilities.",
      "Explain the business or programme context, your responsibilities and the results you can verify. For apparel operations, describe the process you owned; for development work, distinguish project delivery from organisation-wide outcomes. Keep personal contribution visible.",
      "Maintain consistent names, dates and qualifications across your CV, LinkedIn and job-platform profiles. For international applications, adapt terminology and document structure to the destination employer. These packages cover English writing; other language requirements need prior confirmation.",
    ],
    linkedin: [
      "A Bangladesh-facing LinkedIn profile should explain the specialist work behind your title. An operations or programme role benefits from context about the process, stakeholders and responsibilities rather than generic claims about being hardworking.",
      "For overseas or remote opportunities, make your skills and delivery examples understandable to someone unfamiliar with your employer. Keep your current location accurate and protect confidential client information. Account passwords are not needed for a profile rewrite.",
    ],
    strategy: [
      "Choose whether the immediate goal is a Bangladesh role, an overseas move or remote work. These routes may require different target employers and application evidence. Separate them into focused versions instead of trying to serve every goal with one summary.",
      "Prepare examples that show delivery, communication and reliability. Track which requirements recur across suitable vacancies. A consultation can organise priorities and documents while recruitment, immigration and employer decisions remain separate.",
    ],
    headline: "Programme Coordinator | Project Delivery | Stakeholder Communication",
    example: "A programme coordinator can explain the workstream they delivered and its verified result without claiming all outcomes of the wider organisation.",
    question: "Can you prepare separate CVs for Bangladesh and overseas roles?",
    answer: "Yes. Share both target directions so the review can identify the versions required and confirm the scope of a country-specific or bundle service.",
    sources: [{ title: "CV Writer BD: professional and overseas CV services", url: "https://cvwriterbd.com/" }],
  },
  "en-vn": {
    intro: "Explain your experience in clear English for Vietnam-based multinational employers and international teams. A focused CV, professional profile and career strategy help connect practical capability with your intended next role.",
    cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Binh Duong"],
    sectors: ["Technology", "Manufacturing", "Supply chain", "Commercial operations"],
    keywords: ["English CV writing Vietnam", "professional CV Vietnam", "LinkedIn optimization Vietnam", "English resume Vietnam", "career strategy Vietnam"],
    focus: "English CVs for Vietnam that explain technical or commercial work clearly and distinguish language proficiency from job capability.",
    cv: [
      "An English CV for a Vietnam-based opportunity should explain your role without relying on internal titles or literal translations. Identify the business, your responsibilities and the practical results. Keep the language clear enough for a recruiter outside your specialist team.",
      "For manufacturing or supply-chain roles, show the process, supplier or operational responsibility you owned. For software, explain the product and your contribution. A concise achievement is stronger when the reader understands its context.",
      "Use consistent English names for qualifications while retaining details needed to identify them accurately. Describe language proficiency honestly and follow the employer's requested application language. An English CV does not imply that Vietnamese translation is included.",
    ],
    linkedin: [
      "For multinational or international teams in Vietnam, a professional headline can connect your role with a specific capability. Avoid using a translated internal title that gives no indication of what you do.",
      "Use the About section to explain experience across languages, teams or markets with examples. Keep company names and dates consistent with your CV. A portfolio or project link can support technical claims when it is public and appropriate to share.",
    ],
    strategy: [
      "Separate local-language vacancies from roles that explicitly use English. Compare technical requirements and responsibility across Ho Chi Minh City, Hanoi and your other target locations before choosing the strongest application direction.",
      "Prepare an evidence bank for technical work, cross-team communication and problem solving. Use a consultation to clarify how your experience should be presented and which gaps require practice or training. A document rewrite cannot create missing experience.",
    ],
    headline: "Supply Chain Analyst | Manufacturing | Planning & Process Improvement",
    example: "A supply-chain analyst can explain the planning problem, data used and operational decision supported rather than listing spreadsheet skills alone.",
    question: "Are the Vietnam documents written in English?",
    answer: "Yes. This section offers English CV and profile writing. Check the vacancy language and discuss any Vietnamese or bilingual requirement before booking.",
    sources: [{ title: "TopCV Vietnam: English CV format", url: "https://www.topcv.vn/mau-cv-tieng-anh/default_v2" }],
  },
  "en-it": {
    intro: "Position your experience for English-language roles in Italy and international career moves. Build a clear CV, focused LinkedIn profile and professional story that explains your expertise across employers, sectors and countries.",
    cities: ["Milan", "Rome", "Turin", "Bologna"],
    sectors: ["Engineering", "Design", "Manufacturing", "International business"],
    keywords: ["English CV writing Italy", "professional CV writer Italy", "LinkedIn optimisation Italy", "executive CV Milan", "career consultation Italy"],
    focus: "English CVs for Italy with readable professional terminology, relevant portfolio evidence and employer-led format choices.",
    cv: [
      "For an English-language role in Italy, explain your experience in terms the target employer understands. Translate the purpose of the role, not just its title. Retain accurate employer and qualification details so the document remains easy to verify.",
      "An engineering or manufacturing application needs evidence of the process, product or delivery responsibility you owned. Design and other portfolio-led roles can benefit from a carefully selected link. A visual CV should complement, rather than replace, a readable application document when a portal requires one.",
      "Use the format requested by the employer. Do not assume every Italy application requires Europass, a photograph or the same personal information. If a vacancy requests Italian or a particular template, confirm those requirements before choosing the English-writing service.",
    ],
    linkedin: [
      "For a Milan-based international role or an overseas search from Italy, choose a headline that explains your discipline and strongest contribution. A literal translation of a company-specific title may need a plain-English explanation in the experience description.",
      "Connect your profile to relevant work samples where permitted. Explain cross-border responsibilities and language capabilities accurately, keeping dates aligned with the CV. LinkedIn content can support your professional story without claiming access to any particular employer.",
    ],
    strategy: [
      "Separate Italy-based English roles from Italian-language and overseas opportunities. Identify the role requirements, language expectations and portfolio needs before preparing each version of your application.",
      "A consultation can help decide whether your next move depends on clearer positioning, stronger examples or further development. Build an application plan around the employers and responsibilities that fit your experience, then review feedback as the search develops.",
    ],
    headline: "Mechanical Engineer | Product Development | Manufacturing Collaboration",
    example: "An engineer can explain the component or process improved and the collaboration involved without disclosing proprietary product details.",
    question: "Do I need Europass for every job application in Italy?",
    answer: "Follow the employer's instructions. Europass is one option, not a universal requirement. Share any mandatory template or language instructions before the scope is confirmed.",
    sources: [{ title: "FranSyS Consulting: Italy career and CV services", url: "https://www.fransysconsulting.com/en/candidates/" }],
  },
};
